-- Drop tables
DROP TABLE IF EXISTS Product_Category CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Product_Similars CASCADE;
DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS DVD_Person CASCADE;
DROP TABLE IF EXISTS CD_Person CASCADE;
DROP TABLE IF EXISTS Book_Person CASCADE;
DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Purchase CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Offer CASCADE;
DROP TABLE IF EXISTS Title CASCADE;
DROP TABLE IF EXISTS DVD CASCADE;
DROP TABLE IF EXISTS CD CASCADE;
DROP TABLE IF EXISTS Book CASCADE;
DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Shop CASCADE;

